#!/bin/sh

if [[ "$(qdbus6 org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.GetActive)" == "false" && "$(upower -i /org/freedesktop/UPower/devices/line_power_ACAD | grep online | grep -o "yes")" == "yes" ]]; then
  cat /sys/class/backlight/amdgpu_bl1/actual_brightness
elif [[ -f /dev/shm/fpsvw ]]; then
  echo 1
else
  echo 0
fi
