#!/bin/env zsh

#boot strapping creating base environment
local script_path="$(realpath ${(%):-%N})"
local pathprefix_path=""
export activeShell=$(ps -p $$ -o comm=)
local parentShell=$(ps -p $PPID -o comm=)

if [[ $activeShell == "zsh" ]]; then
  pathprefix_path="$script_path"
else
  echo "These dotfiles should only be sourced from zsh not \"$activeShell\""
  return
fi

local knowshells=("bash","fish","sh")
if [[ "$(echo "${knowshells[@]}" | grep -o "$parentShell")" == $parentShell ]] ; then
  echo "These dotfiles are only compatible with ZSH not \"$parentShell\""
  return
fi

local temp="${pathprefix_path%/*}" 

if [[ "$temp" == "." ]] || [[ "$temp" == $pathprefix_path ]] ; then
  local pathprefix_path="."
else 
  local pathprefix_path=$temp
fi

export _path_stack=( "$pathprefix_path" )
export _path_stack_top=1

processRelativePath() {

  p="${_path_stack[$_path_stack_top]}"
  s="$1"

  if [[ "${p:$((${#p}-1)):1}" == "/" ]] ; then 
    p=${p%/*}
  fi

  buffer=""
  buff="${s:0:1}" 
  for ((i=1; i<${#s}; i++)); do
      buff="$buff${s:$i:1}"
      if [[ "$buff" == ".." ]] ; then 
        buff=""
        p="${p%/*}"
        ((i++))
      fi
      if [[ "${#buff}" -eq 2 ]] ; then 
        buffer="$buffer${buff:0:1}"
        buff="${buff:1:1}"
      fi
  done

  buffer="$p/$buffer$buff"
  newtop=$buffer
  if [[ "${newtop:$((${#newtop}-1)):1}" != "/" ]] ; then 
    newtop=${newtop%/*}
  fi

  ((_path_stack_top++))
  _path_stack[_path_stack_top]="$newtop"

  shift

  source "$buffer" $*

  unset "_path_stack[-1]"
  ((_path_stack_top--))
}

processRelativePath runtime/helper debug shell type $activeShell
processRelativePath runtime/helper debug $pathprefix_path

# further processing
# the first argument should always be --init
processRelativePath runtime/initscript $1 "--p=$script_path"
