#!/bin/zsh

local _dot_flag_enable() {
  $_dot_files_root_dir/runtime/logger debug "Enable Flag : $1"
  echo "$1" >> $_dot_files_root_dir/config/FLAGS
  export $1=1
}

local _dot_flag_disable() {
  $_dot_files_root_dir/runtime/logger debug "Disable Flag : $1"
  if [[ -f $_dot_files_root_dir/config/FLAGS_$1 ]] ; then
    rm $_dot_files_root_dir/config/FLAGS_$1
  fi
  touch $_dot_files_root_dir/config/FLAGS_$1
  while read -r line; do
    if [[ $line != $1 ]] ; then
      echo "$line" >> $_dot_files_root_dir/config/FLAGS_$1
    fi
  done < $_dot_files_root_dir/config/FLAGS
  mv $_dot_files_root_dir/config/FLAGS_$1 $_dot_files_root_dir/config/FLAGS
  unset $1
}

dotListFlag() {
  local RED="\e[1;31m"
  local GREEN=$'\e[1;32m'
  local RESET="\e[0m"
  local TICK="✓"
  local CROSS="✗"
  local output="$(while read -r line ; do 
    if [[ "$(grep -o "$line" $_dot_files_root_dir/config/FLAGS)" == $line ]] ; then
      printf "${GREEN}${TICK}${RESET} "
    else
      printf "${RED}${CROSS}${RESET} "
    fi
    echo "$line"
  done < $_dot_files_root_dir/runtime/LIST_OF_FLAGS )" 
  if [[ -v DISABLE_DOT_LIST_PAGER ]] ; then
    echo $output
  else 
    echo $output | less 
  fi
}

dotToggleflags() {
  local CROSS="✗"
  DISABLE_DOT_LIST_PAGER=1
  local output="$(dotListFlag | fzf --ansi)"
  if [[ $output == "" ]] ; then
    return
  fi
  if [[ "$(echo $output| awk '{ print $1 }')" == $CROSS ]] ; then
    _dot_flag_enable "$(echo $output | awk '{ print $2 }')"
  else
    _dot_flag_disable "$(echo $output | awk '{ print $2 }')"
  fi
  unset DISABLE_DOT_LIST_PAGER
}
