#!/bin/zsh
local script_path="${_path_stack[$_path_stack_top]}"
local mainSourceScriptPath="$( echo $* | grep -o -- "--p=.*" | sed -e 's#--p=##g' )"

if [[ "$1" == "--init" ]] ; then
  export LOGERROR=0
  processRelativePath logger debug setting up the environment
  processRelativePath setup
else 
  processRelativePath logger debug initializing the environment
  processRelativePath initialize
fi
