#!/bin/zsh

RED="\e[1;31m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
RESET="\e[0m"

error() {
  if [[ -v LOGERROR ]] ; then
    printf "${RED}[ERROR]${RESET} %s\n" "$*" >&2
  fi
}

warn() {
  if [[ -v LOGERROR ]] || [[ -v LOGWARN ]] ; then
    printf "${YELLOW}[WARN]${RESET} %s\n" "$*" >&2
  fi
}

debug() {
  if [[ -v LOGERROR ]] || [[ -v LOGWARN ]] || [[ -v LOGDEBUG ]] ; then
    printf "${BLUE}[DEBUG]${RESET} %s\n" "$*"
  fi
}

# call logger function
$@
