#!/bin/zsh

processRelativePath logger debug entered module loader

local modules="$(printRelativePath ../module)"
local modulePrefix="$( printRelativePath ../module/ )"
local enaledModules=$(cat $(printRelativePath ../config/LOAD_MODULE ) | tr '\n' ' ' )
local loadedModule=()

processRelativePath logger debug enabled modules ${enaledModules[@]}

local loadModule() {
  _failedStatus=0
  local file=$1
  if [[ ! -f $modulePrefix$file ]] ; then 
    _failedStatus=1
    processRelativePath logger error "Module is mentions but doesn't exist : $file"
    return
  fi
  local header=$( grep " *#!.*" $modulePrefix$file )
  if [[ $header == "#!/bin/bash" ]] || [[ $header == "#!/bin/zsh" ]] ||  [[ $header == "#!/bin/sh" ]] ||  \
    [[ $header == "#!/bin/env bash" ]] || [[ $header == "#!/bin/env zsh" ]] ||  [[ $header == "#!/bin/env sh" ]] ; then
    processRelativePath logger debug "Loading module : $file"
    resolveDependency $modulePrefix$file
  else 
    _failedStatus=1
    processRelativePath logger error "Module doesn't have script header ( i.e. #! ) : $file"
  fi
}

local resolveDependency() {
  local script=$1
  if [[ "${loadedModule[@]}" =~ ".*$script.*" ]] ; then 
    processRelativePath logger debug "Duplicate module entry or requested by other module ${script#$modulePrefix}" 
    return
  fi
  loadedModule+=($script)
  grep " *#->.*" $script | tr '\n' ',' | xargs echo | sed -e 's/#->//g' \
    | while read -r -d ',' module; do
    module="${module// /}"
    processRelativePath logger debug "Loading module as dependency $module" 
    loadModule $module
    if [[ $_failedStatus == 1 ]] ; then
      unset _failedStatus
      processRelativePath logger error "Failed to load module ${script#$modulePrefix} depends on $module"
      return
    fi
    unset _failedStatus
  done

  if [[ -v SILENT_MODULE_LOAD ]] ; then
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script > /dev/null 2>&1 
    else
      source $script > /dev/null
    fi
  #elif [[ -v LOG_MODULE_LOAD ]] ; then 
  #  #if [[ -d /dev/shm/logs ]] ; then 
  #  #  mkdir /dev/shm/logs
  #  #fi
  #  #if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
  #  #  source $script > /dev/shm/logs/$1_log 2>&1 
  #  #else
  #  #  source $script > /dev/shm/logs/$1_log 
  #  #fi
  #  if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
  #    source $script 2>&1 | xargs ${_dot_files_root_dir}runtime/logger debug 
  #  else
  #    source $script | xargs ${_dot_files_root_dir}runtime/logger debug 
  #  fi
  else
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script 2>&1
    else
      source $script
    fi
  fi
  processRelativePath logger debug "Loaded module ${script#$modulePrefix}" 
}

while IFS= read -r file; do
  loadModule $file 
done < $(printRelativePath ../config/LOAD_MODULE )

# option to force load modules
if [[ -v forcedModules ]] ; then 
  for module in  ${forcedModules[@]} ; do 
    debug "Loading Forced Module : $module"
    loadModule $module
  done
fi
