#!/bin/zsh

debug entered module loader

local modules="$(printRelativePath ../module)"
local modulePrefix="$( printRelativePath ../module/ )"
local enaledModules=$(cat $(printRelativePath ../config/LOAD_MODULE ) | tr '\n' ' ' )
local loadedModule=()

debug enabled modules ${enaledModules[@]}

local loadModule() {
  _failedStatus=0
  local file=$1
  if [[ ! -f $modulePrefix$file ]] ; then 
    _failedStatus=1
    error "Module is mentions but doesn't exist : $file"
    return
  fi
  local header=$( grep " *#!.*" $modulePrefix$file )
  if [[ $header == "#!/bin/bash" ]] || [[ $header == "#!/bin/zsh" ]] ||  [[ $header == "#!/bin/sh" ]] ||  \
    [[ $header == "#!/bin/env bash" ]] || [[ $header == "#!/bin/env zsh" ]] ||  [[ $header == "#!/bin/env sh" ]] ; then
    debug "Loading module : $file"
    resolveDependency $modulePrefix$file
  else 
    _failedStatus=1
    error "Module doesn't have script header ( i.e. #! ) : $file"
  fi
}

local resolveDependency() {
  local script=$1
  if [[ "${loadedModule[@]}" =~ ".*$script.*" ]] ; then 
    debug "Duplicate module entry or requested by other module ${script#$modulePrefix}" 
    return
  fi
  loadedModule+=($script)
  grep " *#->.*" $script | tr '\n' ',' | xargs echo | sed -e 's/#->//g' \
    | while read -r -d ',' module; do
    module="${module// /}"
    debug "Loading module as dependency $module" 
    loadModule $module
    if [[ $_failedStatus == 1 ]] ; then
      unset _failedStatus
      error "Failed to load module ${script#$modulePrefix} depends on $module"
      return
    fi
    unset _failedStatus
  done

  if [[ -v SILENT_MODULE_LOAD ]] ; then
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script > /dev/null 2>&1 
    else
      source $script > /dev/null
    fi
  #elif [[ -v LOG_MODULE_LOAD ]] ; then 
  #  #if [[ -d /dev/shm/logs ]] ; then 
  #  #  mkdir /dev/shm/logs
  #  #fi
  #  #if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
  #  #  source $script > /dev/shm/logs/$1_log 2>&1 
  #  #else
  #  #  source $script > /dev/shm/logs/$1_log 
  #  #fi
  #  if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
  #    source $script 2>&1 | xargs ${_dot_files_root_dir}runtime/logger debug 
  #  else
  #    source $script | xargs ${_dot_files_root_dir}runtime/logger debug 
  #  fi
  else
    if [[ -v REDIRECT_ERROR_TO_OUTPUT_MODULE_LOAD ]] ; then 
      source $script 2>&1
    else
      source $script
    fi
  fi
  debug "Loaded module ${script#$modulePrefix}" 
}

if [[ ! -f ${_dot_files_root_dir}config/POST_LOAD_MODULE ]] ; then
  touch ${_dot_files_root_dir}config/POST_LOAD_MODULE
fi

# Fix the priority loading loop and the phantom $line bug
if [[ -f ${_dot_files_root_dir}config/PRE_LOAD_MODULE ]] ; then
  while IFS= read -r module <&3 ; do
    if [[ "${enaledModules[@]}" =~ ".*$module.*" ]] ; then
      debug "Loading PRE_LOAD_MODULE : $module"
      loadModule "$module"
    else
      warn "$module is mentioned in PRE_LOAD_MODULE but isn't enabled"
    fi
  done 3< "${_dot_files_root_dir}config/PRE_LOAD_MODULE"
else
  touch ${_dot_files_root_dir}config/PRE_LOAD_MODULE
fi

local postLoadModules="$( cat ${_dot_files_root_dir}config/POST_LOAD_MODULE | tr '\n' ' ' )"

# Fix the normal loading loop
while IFS= read -r module <&3; do
  if [[ ${postLoadModules} =~ ".*$module.*" ]] ; then
    debug "Module is in POST_LOAD_MODULE $module so will be loaded later"
  else
    loadModule "$module"
  fi
done 3< "${_dot_files_root_dir}config/LOAD_MODULE"


# option to force load modules
if [[ -v forcedModules ]] ; then 
  for module in  ${forcedModules[@]} ; do 
    if [[ ${postLoadModules} =~ ".*$module.*" ]] ; then
      debug "Module is in POST_LOAD_MODULE $module so will be loaded later"
    else
      debug "Loading Forced Module : $module"
      loadModule $module
    fi
  done
fi

while IFS= read -r module <&3 ; do
  if [[ "${enaledModules[@]}" =~ ".*$module.*" ]] ; then
    debug "Loading POST_LOAD_MODULE : $module"
    loadModule "$module"
  else
    warn "$module is mentioned in POST_LOAD_MODULE but isn't enabled"
  fi
done 3< "${_dot_files_root_dir}config/POST_LOAD_MODULE"
