#!/bin/zsh
fzf-history-widget() {
  
  local cmd
  cmd=$( fc -l 1 | sed 's/^[ ]*[0-9]*[ ]*//' | awk '{ if ( seen[$0]++ == 0 ) { print }}' | tac | fzf --preview-window=wrap --preview 'echo {} | bat --decorations=never --language=zsh --wrap=auto --color=always')

  if [[ -n $cmd ]]; then
    BUFFER="$cmd"
    CURSOR=${#BUFFER}
  fi
}

zle -N fzf-history-widget
bindkey '^R' fzf-history-widget
