#! /usr/bin/env bash

asciiFile="/etc/grub.d/ascii_art"
grubFile="/etc/grub.d/10_linux"

firstChange() {

  cp $grubFile "$grubFile.bak"
  chmod -x "$grubFile.bak"

  linux_command="$(cat $grubFile | pcregrep -M 'linux_entry \(\) ?\n?{(.|\n)*' | grep "linux.*root=.*")"
  #indentation="$(echo "$linux_command" | grep -oP '^[\s]*')"
  ascii_art_buff="$(sed -e "s/\(.*\)/echo \"\1\"/g" $asciiFile)"

  if [[ -f "$grubFile.mod" ]]; then

    rm "$grubFile.mod"

  fi

  while IFS= read -r line; do

    if [[ "$line" == "$linux_command" ]]; then
      echo "$ascii_art_buff" >>"$grubFile.mod"
    fi

    echo "$line" >>"$grubFile.mod"
  done <$grubFile
  echo "ascii_art_hash=$1" >>"$grubFile.mod"
  mv "$grubFile.mod" $grubFile
  chmod +x "$grubFile"

}

if
  [[ -f $grubFile ]] &
  [[ -f /etc/grub.d/ascii_art ]]
then
  buffer="$(cat $grubFile)"
  ascii_art_hash=$(sha256sum $asciiFile | grep -o ".*\s")
  buffer_ascii_art_hash="$(cat $grubFile | grep "ascii_art_hash" | sed -e 's/ascii_art_hash=//g')"
  buffer_ascii_art_hash="${buffer_ascii_art_hash%%[[:space:]]*}"
  ascii_art_hash="${ascii_art_hash%%[[:space:]]*}"

  if [[ $1 == "-lv" ]]; then
    echo "ascii hash  : \"$ascii_art_hash\""
    echo "buffer hash : \"$buffer_ascii_art_hash\""
    exit
  fi

  if [[ $buffer_ascii_art_hash == "" ]]; then
    echo "Unmodified"
    firstChange $ascii_art_hash
  elif [[ $buffer_ascii_art_hash != $ascii_art_hash ]]; then
    echo "Changes Detected"
    cp "$grubFile.bak" $grubFile
    firstChange $ascii_art_hash
  else
    echo "No Changes"
  fi

fi
