#!/bin/env bash

# add these at the start of the config
#import os
#
#container_running = "/dev/shm/startInContainer"
#
## Check if file exists, then delete
#if os.path.exists(container_running):
#    os.remove(container_running)
#else:
#    with open(container_running, 'w'):
#        pass
#    subprocess.run("bash $HOME/.config/qutebrowser/userscripts/startInContainer", shell=True, executable="/bin/bash")
#    quit()
#
#def read_xresources(prefix):
#    props = {}
#    x = subprocess.run(['xrdb', '-query'],
#                       capture_output=True, check=True, text=True)
#    lines = x.stdout.split('\n')
#    for line in filter(lambda l: l.startswith(prefix), lines):
#        prop, _, value = line.partition(':\t')
#        props[prop] = value
#    return props
#

createContainer() {

  newContainer="$(zenity --entry \
    --title="Create a new container" \
    --text="Enter name of new container:" \
    --entry-text "default")"

  . $(dirname $0)/container-add "$newContainer"

  selectAContainer

}

selectAContainer() {

  title="qutebrowser"
  prompt="Select A container to start"
  items=($(cd "$(dirname $0)" && cd .. && cat containers))
  #items=($(cat $HOME/.config/qutebrowser/containers))

  if [[ "${#items}" == 0 ]]; then
    echo "No Conatiner Found"
    createContainer
    return -1
  fi

  items+=(anonymous "new container")

  item=$(zenity --title="$title" --text="$prompt" --list --column="containers" "${items[@]}")

  if [[ $item == "new container" ]]; then
    createContainer
    return 0
  fi

  if [[ $item == "anonymous" ]]; then
    if [[ -f "/dev/shm/qbcco" ]]; then
      rm /dev/shm/qbcco
    fi
    echo 'CONTAINER_BASE="/dev/shm/qutebrowser"' >>/dev/shm/qbcco
    echo 'CONTAINER_LIST="/dev/shm/qc"' >>/dev/shm/qbcco
    touch /dev/shm/qc
    . $(dirname $0)/container-add anonymous
    . $(dirname $0)/container-open anonymous
    . $(dirname $0)/container-rm anonymous
    rm /dev/shm/qbcco
    rm /dev/shm/qc
    rm -r /dev/shm/qutebrowser/
    return 0
  fi

  . $(dirname $0)/container-open $item
}

selectAContainer
